version: '3.1'
services:

  db:
    hostname: db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: task
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
